SELECT T.DEPT_ID, T.USER_ID, T.HIRE_DATE
FROM
    (SELECT
    U.DEPT_ID,
    U.USER_ID,
    U.HIRE_DATE
    REAK() OVER (PARTITION BY DEPT_ID ORDER BY HIRE_DATE ASC) AS rnk
FROM USERS U
) AS T
WHERE RNK = 1
ORDER BY DEPT_ID, HIRE_DATE, USER_ID;