SELECT P.PRODUCT_ID,
       P.PRICE,
       SUBSTRING(PRODUCT_CODE,1,2) AS CATEGORY,
       MAX(P.PRICE) AS MAX_PRICE
FROM PRODUCT P
GROUP BY SUBSTRING(PRODUCT_CODE,1,2)
ORDER BY CATEGORY, PRODUCT ID;